#!/usr/bin/env php

<?php

use Medpets\Assignments\CreateProjectCommand;

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Medpets Assignment', '1.0.0');
$app->add(new CreateProjectCommand());
$app->run();
